# Datetime variables in Python and pandas

Date and time features are important for data science problems in various industries, from sales, marketing, and finance to HR, e-commerce, retail, and many more. Predicting how the stock markets will behave tomorrow, how many products will be sold in the upcoming week, when is the best time to launch a new product, how long before a position at the company gets filled, etc. are some of the problems that we can find answers to using date and time data.

This incredible amount of insight that you can unravel from the data is what makes date and time components so fun to work with! So let’s get down to the business of mastering date-time manipulation in Python.

But in many cases dates and time are not in the right format and the information in those variables can't be worked with until it is transformed.

In the following notebook you will learn how to work with dates and time in `Python` and `pandas`.

In [25]:
import pandas as pd
from datetime import datetime, date, time, timedelta

### Python Datetime Module

First, we will have a look at the datetime module of Python. Let's start simple. We will look at the basics of the module and how to define dates and time.

In [26]:
# We create a date variable for a random date with the datetime module and as a string…
d1 = date(2021, 5, 14)
d2 = '2021-05-14'

# …and print out the variables. Do you see any differences?
print(d1)
print(d2)

2021-05-14
2021-05-14

In [27]:
# If we have a look at the types of those two variables we can see that there is a difference.
print(type(d1))
print(type(d2))

<class 'datetime.date'>
<class 'str'>

In [28]:
# You can also easily create a variable with the date of today.
d3 = date.today()
print('Date of today: ',d3)

# You can print the day…
print('Day: ', d3.day)

# …or month…
print('Month: ', d3.month)

# …or year.
print('Year: ', d3.year)

Date of today:  2026-03-13
Day:  13
Month:  3
Year:  2026

In [29]:
# The same applies to the time method.
t1 = time(13, 20, 13, 40)
t2 = '13:20:13.000040'
print(t1)
print(t2)
print(type(t1))
print(type(t2))

13:20:13.000040
13:20:13.000040
<class 'datetime.time'>
<class 'str'>

In [30]:
# You can print the hour…
print('Hour :',t1.hour)

# …or minute…
print('Minute :',t1.minute)

# …or second…
print('Second :',t1.second)

# …and even the microseconds.
print('Microsecond :',t1.microsecond)

Hour : 13
Minute : 20
Second : 13
Microsecond : 40

Above we looked at the date and time separately with the `date` and `time` methods. But we can also combine both with the `datetime` method.

In [31]:
# We create a variable with a random date and time with the datetime method…
dt1 = datetime(2021, 5, 14, 11, 20, 30, 40)

# …and print it.
print(dt1)
print(type(dt1))

2021-05-14 11:20:30.000040
<class 'datetime.datetime'>

In [32]:
# You can also create a variable with your local date-time.
dt2 = datetime.now()
dt2

datetime.datetime(2026, 3, 13, 11, 41, 35, 732806)

One really cool thing you can do with the DateTime function is to extract the day of the week! This is especially helpful in feature engineering because the value of the target variable can be dependent on the day of the week, like sales of a product are generally higher on a weekend or traffic on StackOverflow could be higher on a weekday when people are working, etc.

>Note: `.weekday` returns the day of the week starting with 0 for Monday and ending with 6 for Sunday. `.isoweekday` on the other hand returns the day of the week where Monday is 1 and Sunday is 7.

In [33]:
# We can define the date of today…
dt2 = datetime.now()

# …and print the weekday where Monday is 0…
print(dt2.weekday()) # outputs e.g. 3 for Thursday

# …or where Monday is 1.
print(dt2.isoweekday()) # outputs 4 in ISO format

4
5

Another very important feature that you can generate from the given date in a dataset is the week of the year.

In [34]:
# We can define the date of today…
dt2 = datetime.now()

# …and return the year, week and weekday. 
print('Date:', dt2.isocalendar())
print('Week :', dt2.isocalendar()[1])

Date: datetime.IsoCalendarDate(year=2026, week=11, weekday=5)
Week : 11

### Formatting the dates with `strptime` and `strftime`

As we saw in the first example, you have to pay attention to the type of the data. The date in datasets often is of type string. So how can we change that?

- `strptime`: creates a `datetime` object from a string representing date and time. It takes two arguments: the date and the format in which your date is present.
- `strftime`: can be used to convert the `datetime` object into a string representing date and time.

The following table shows several format codes that can be used to specify a date or time format. 
<style>
table th:first-of-type {
    width: 10%;
}
table th:nth-of-type(2) {
    width: 65%;
}
table th:nth-of-type(3) {
    width: 25%;
}
</style>

| Directive | Meaning | Example |
|:- | :-:| -:|
| %a | Abbreviated weekday name. | Sun, Mon, ...|
| %A | Full weekday name. | Sunday, Monday, ... |
| %w |	Weekday as a decimal number. |	0, 1, ..., 6 |
| %d |	Day of the month as a zero-padded decimal. |	01, 02, ..., 31 |
| %-d |	Day of the month as a decimal number.|	1, 2, ..., 30|
| %b |	Abbreviated month name.|	Jan, Feb, ..., Dec|
| %B |	Full month name.|	January, February, ...|
| %m |	Month as a zero-padded decimal number.|	01, 02, ..., 12|
| %-m |	Month as a decimal number.|	1, 2, ..., 12|
| %y |	Year without century as a zero-padded decimal number.|	00, 01, ..., 99|
| %-y |	Year without century as a decimal number.|	0, 1, ..., 99|
| %Y |	Year with century as a decimal number.|	2013, 2019 etc.|
| %H |	Hour (24-hour clock) as a zero-padded decimal number.|	00, 01, ..., 23|
| %-H |	Hour (24-hour clock) as a decimal number.|	0, 1, ..., 23|
| %I |	Hour (12-hour clock) as a zero-padded decimal number.|	01, 02, ..., 12|
| %-I |	Hour (12-hour clock) as a decimal number.|	1, 2, ... 12|
| %p|	Locale’s AM or PM.|	AM, PM|
| %M|	Minute as a zero-padded decimal number.|	00, 01, ..., 59|
| %-M|	Minute as a decimal number.|	0, 1, ..., 59|
| %S|	Second as a zero-padded decimal number.|	00, 01, ..., 59|
| %-S|	Second as a decimal number.|	0, 1, ..., 59|
| %f|	Microsecond as a decimal number, zero-padded on the left.|	000000 - 999999|
| %z|	UTC offset in the form +HHMM or -HHMM.|	| 
| %Z|	Time zone name.|	 |
| %j|	Day of the year as a zero-padded decimal number.|	001, 002, ..., 366|
| %-j|	Day of the year as a decimal number.|	1, 2, ..., 366|
| %U|	Week number of the year (Sunday as the first day of the week). All days in a new year preceding the first Sunday are considered to be in week 0.|	00, 01, ..., 53|
| %W|	Week number of the year (Monday as the first day of the week). All days in a new year preceding the first Monday are considered to be in week 0.|	00, 01, ..., 53|
| %c|	Locale’s appropriate date and time representation.|	Mon Sep 30 07:06:05 2013|
| %x|	Locale’s appropriate date representation.|	09/30/13|
| %X|	Locale’s appropriate time representation.|	07:06:05|
| %%|	A literal '%' character.|	%|

#### Strptime

With `strptime` and the right combination of the format codes (see list above) you can convert a string into a datetime type:

In [35]:
# Create a variable with a datetime stored as string…
date = '22 April, 2020 13:20:13'

# …and convert the string to datetime type.
d1 = datetime.strptime(date,'%d %B, %Y %H:%M:%S')
print(d1)
print(type(d1))

2020-04-22 13:20:13
<class 'datetime.datetime'>

In [36]:
# We can create a date stored as string…
date = '2021-05-14'
print(date)
print(type(date))

# …and convert the string to datetime…
d2 = datetime.strptime(date, '%Y-%m-%d')
print(d2)
print(type(d2))

# …or convert the string to date format. 
d2 = datetime.strptime(date, '%Y-%m-%d').date()
print(d2)
print(type(d2))

2021-05-14
<class 'str'>
2021-05-14 00:00:00
<class 'datetime.datetime'>
2021-05-14
<class 'datetime.date'>

#### Strftime


If we want to convert a `datetime` variable into a string we can use `.strftime` and the right combination of format codes:

In [37]:
# Create a datetime variable…
d1 = datetime.now()
print('Datetime object :',d1)

# …and convert it into a string.
new_date = d1.strftime('%d/%m/%Y %H:%M')
print('Formatted date :',new_date)
print(type(new_date))

Datetime object : 2026-03-13 11:41:36.136337
Formatted date : 13/03/2026 11:41
<class 'str'>

### Calculating with the datetime module

Sometimes, you might have to find the time span between two dates, which can be another very useful feature that you can derive from a dataset. By subtracting one date from another you will get a `timedelta`.

In [38]:
# timedelta : duration between dates
d1 = datetime(2020,4,23,11,13,10)
d2 = datetime(2021,4,23,12,13,10)
duration = d2 - d1
print(type(duration))
duration

<class 'datetime.timedelta'>

datetime.timedelta(days=365, seconds=3600)

As you can see, the duration is returned as the number of days for the date and seconds for the time between the dates. So for your features you can also retrieve those values separately:

In [39]:
print('Duration:', duration)
print('Days:', duration.days) # 365
print('Seconds:' ,duration.seconds) # 3600

Duration: 365 days, 1:00:00
Days: 365
Seconds: 3600

But what if you actually need the duration in hours or minutes? Well, there is a simple solution for that.

`timedelta` is also a class in the `datetime` module. So, you can use it to convert your duration into hours and minutes as the following code shows:

In [40]:
# duration in hours
print('Duration in hours :', duration / timedelta(hours = 1))

# duration in minutes
print('Duration in minutes :', duration / timedelta(minutes = 1))

# duration in seconds
print('Duration in seconds :', duration / timedelta(seconds = 1))

Duration in hours : 8761.0
Duration in minutes : 525660.0
Duration in seconds : 31539600.0

`timedelta` also makes it possible to add and subtract integers from a `datetime` object.

In [41]:
# Create datetime variable for current date…
d1 = datetime.now().date()
print("Today's date :",d1)

# …and add two days…
d2 = d1+timedelta(days=2)
print("Date 2 days from today :",d2)

# …or add two weeks.
d3 = d1+timedelta(weeks=2)
print("Date 2 weeks from today :",d3)

Today's date : 2026-03-13
Date 2 days from today : 2026-03-15
Date 2 weeks from today : 2026-03-27

## DateTime in pandas

We already know that pandas is a great library for doing data analysis tasks. And so it goes without saying that pandas also supports Python DateTime objects. It has some great methods for handling dates and times, such as `to_datetime()` and `to_timedelta()`.

In [42]:
# Define a date using .to_datetime()
date = pd.to_datetime('24th of April, 2020')
print(date)
print(type(date))

2020-04-24 00:00:00
<class 'pandas.Timestamp'>

You might have noticed something strange here. The type of the object returned by `.to_datetime()` is not DateTime but Timestamp. Well, don’t worry, it is just the pandas equivalent of Python’s DateTime.

We already know that time delta gives differences in times. The Pandas `.to_timedelta()` method does the same:

In [43]:
# Define and print a variable with the current date and time…
date = datetime.now()
print(date)

# …and print the date of tomorrow…
print(date + pd.to_timedelta(1, unit = 'D'))

# …and next week.
print(date + pd.to_timedelta(1, unit = 'W'))

2026-03-13 11:41:36.226774
2026-03-14 11:41:36.226774
2026-03-20 11:41:36.226774

### Date Range in pandas

To make the creation of date sequences a convenient task, pandas provides the `.date_range()` method. It accepts a start date, an end date, and an optional frequency code:

In [44]:
# Create a range of dates for 1 month
pd.date_range(start='24/4/2020', end='24/5/2020', freq='D')

DatetimeIndex(['2020-04-24', '2020-04-25', '2020-04-26', '2020-04-27',
               '2020-04-28', '2020-04-29', '2020-04-30', '2020-05-01',
               '2020-05-02', '2020-05-03', '2020-05-04', '2020-05-05',
               '2020-05-06', '2020-05-07', '2020-05-08', '2020-05-09',
               '2020-05-10', '2020-05-11', '2020-05-12', '2020-05-13',
               '2020-05-14', '2020-05-15', '2020-05-16', '2020-05-17',
               '2020-05-18', '2020-05-19', '2020-05-20', '2020-05-21',
               '2020-05-22', '2020-05-23', '2020-05-24'],
              dtype='datetime64[us]', freq='D')

Instead of defining the end date, you could also define the period or number of time periods you want to generate: [See here for a list of frequency aliases.]( https://pandas.pydata.org/docs/user_guide/timeseries.html#timeseries-offset-aliases)

In [45]:
# Define variable with date of today…
start_date = datetime.today()

# …and create sequence with consecutive minutes…  
dates_start = pd.date_range(start=start_date, periods=10, freq='min')
dates_start

DatetimeIndex(['2026-03-13 11:41:36.384069', '2026-03-13 11:42:36.384069',
               '2026-03-13 11:43:36.384069', '2026-03-13 11:44:36.384069',
               '2026-03-13 11:45:36.384069', '2026-03-13 11:46:36.384069',
               '2026-03-13 11:47:36.384069', '2026-03-13 11:48:36.384069',
               '2026-03-13 11:49:36.384069', '2026-03-13 11:50:36.384069'],
              dtype='datetime64[us]', freq='min')

In [46]:
# …or consecutive days. 
dates_end = pd.date_range(start=start_date, periods=10, freq='D')
dates_end

DatetimeIndex(['2026-03-13 11:41:36.384069', '2026-03-14 11:41:36.384069',
               '2026-03-15 11:41:36.384069', '2026-03-16 11:41:36.384069',
               '2026-03-17 11:41:36.384069', '2026-03-18 11:41:36.384069',
               '2026-03-19 11:41:36.384069', '2026-03-20 11:41:36.384069',
               '2026-03-21 11:41:36.384069', '2026-03-22 11:41:36.384069'],
              dtype='datetime64[us]', freq='D')

Let's have a look at how to create new features out of `datetime/timestamp` columns in a pandas DataFrame. Therefore, we will create a little DataFrame which contains the `start_date` and `end_date` (see cells above) as features and a target column with three different classes.

In [47]:
# Create target column with random classes (1, 2 or 3)
import random
randomList = []
for i in range(10):
    randomList.append(random.randint(1,3))

# Create DataFrame out of previously defined variables
df = pd.DataFrame()
df['Start_date'] = dates_start
df['End_date'] = dates_end
df['Target'] = randomList

# Show first 5 rows 
df.head()

                  Start_date                   End_date  Target
0 2026-03-13 11:41:36.384069 2026-03-13 11:41:36.384069       2
1 2026-03-13 11:42:36.384069 2026-03-14 11:41:36.384069       3
2 2026-03-13 11:43:36.384069 2026-03-15 11:41:36.384069       2
3 2026-03-13 11:44:36.384069 2026-03-16 11:41:36.384069       3
4 2026-03-13 11:45:36.384069 2026-03-17 11:41:36.384069       2

In [48]:
# The elements in the date columns are still timestamps 
print(df.Start_date[0])
print(type(df.Start_date[0]))

2026-03-13 11:41:36.384069
<class 'pandas.Timestamp'>

We can create multiple new features from the date column, like the day, month, year, hour, minute, etc. using the `dt` attribute. For example, let's create a new column containing the information about the day of our `end_date` column.

In [49]:
# Create new column with day of end_date column
df['Day_of_end_date'] = df['End_date'].dt.day
df.head(10)

,Start_date,End_date,Target,Day_of_end_date
0,2026-03-13 11:41:36.384069,2026-03-13 11:41:36.384069,2,13
1,2026-03-13 11:42:36.384069,2026-03-14 11:41:36.384069,3,14
2,2026-03-13 11:43:36.384069,2026-03-15 11:41:36.384069,2,15
3,2026-03-13 11:44:36.384069,2026-03-16 11:41:36.384069,3,16
4,2026-03-13 11:45:36.384069,2026-03-17 11:41:36.384069,2,17
5,2026-03-13 11:46:36.384069,2026-03-18 11:41:36.384069,3,18
6,2026-03-13 11:47:36.384069,2026-03-19 11:41:36.384069,2,19
7,2026-03-13 11:48:36.384069,2026-03-20 11:41:36.384069,3,20
8,2026-03-13 11:49:36.384069,2026-03-21 11:41:36.384069,2,21
9,2026-03-13 11:50:36.384069,2026-03-22 11:41:36.384069,2,22

In [50]:
# Create new column for year of start_date column
df['Year_of_start_date'] = df['Start_date'].dt.year
df.head()

,Start_date,End_date,Target,Day_of_end_date,Year_of_start_date
0,2026-03-13 11:41:36.384069,2026-03-13 11:41:36.384069,2,13,2026
1,2026-03-13 11:42:36.384069,2026-03-14 11:41:36.384069,3,14,2026
2,2026-03-13 11:43:36.384069,2026-03-15 11:41:36.384069,2,15,2026
3,2026-03-13 11:44:36.384069,2026-03-16 11:41:36.384069,3,16,2026
4,2026-03-13 11:45:36.384069,2026-03-17 11:41:36.384069,2,17,2026

## Exercise:

Create at least two more features for example `month`, `hour` or `minute` etc. from the start and end date columns.

In [51]:
# Your code here!
df['Month_of_start_date'] = df['Start_date'].dt.month
df.head()

,Start_date,End_date,Target,Day_of_end_date,Year_of_start_date,Month_of_start_date
0,2026-03-13 11:41:36.384069,2026-03-13 11:41:36.384069,2,13,2026,3
1,2026-03-13 11:42:36.384069,2026-03-14 11:41:36.384069,3,14,2026,3
2,2026-03-13 11:43:36.384069,2026-03-15 11:41:36.384069,2,15,2026,3
3,2026-03-13 11:44:36.384069,2026-03-16 11:41:36.384069,3,16,2026,3
4,2026-03-13 11:45:36.384069,2026-03-17 11:41:36.384069,2,17,2026,3

In [52]:
# Your code here!
df['Minute_of_end_date'] = df['End_date'].dt.minute
df.head()

,Start_date,End_date,Target,Day_of_end_date,Year_of_start_date,Month_of_start_date,Minute_of_end_date
0,2026-03-13 11:41:36.384069,2026-03-13 11:41:36.384069,2,13,2026,3,41
1,2026-03-13 11:42:36.384069,2026-03-14 11:41:36.384069,3,14,2026,3,41
2,2026-03-13 11:43:36.384069,2026-03-15 11:41:36.384069,2,15,2026,3,41
3,2026-03-13 11:44:36.384069,2026-03-16 11:41:36.384069,3,16,2026,3,41
4,2026-03-13 11:45:36.384069,2026-03-17 11:41:36.384069,2,17,2026,3,41

## Working with dates on a real dataset

At the end of this notebook we will have a quick look at a real dataset with weather information for the city of Seattle. You will see that the first column contains information about the date of the measurements. While importing the dataset this column is loaded as a object/string type column and we want to convert it before we start our analysis.

In [53]:
# Loading the dataset
df = pd.read_csv("data/seattle-weather.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'data/seattle-weather.csv'

In [ ]:
# Check if the data is loaded correctly
df.head()

In [ ]:
# Check column types 
df.info()

In [ ]:
print(df.date[0])
print(type(df.date[0]))

From the output of `df.info()` and the two print statements above we can see that the date column is loaded as object/string. 
In order to facilitate working with the date column we can change the type using `.to_datetime()`:

In [ ]:
# Replace original column with converted one 
df.date = pd.to_datetime(df.date, format='%Y/%m/%d')

In [ ]:
df.head()

In [ ]:
df.info()

In [ ]:
print(df.date[0])
print(type(df.date[0]))

And now the date column is correctly defined as datetime.

## Summary

In addition to strings, floats and integers, there is another data type specific to dates and time (datetime).
If you are dealing with time-dependent data, it is worth to convert them into the correct datetime format.
This ensures that
- it's easy to choose the desired format of the date (e.g. YY-MM-DD)
- durations are calculated correctly
- durations can be displayed in different time units easily (e.g. in hours or days)
- additional features can be easily created (e.g. what day of the week it is)
- visualization tools can recognize variables correctly and display them well (axis labeling).